name: Build toolchain

on:
  workflow_call:
    inputs:
      nightly:
        required: false
        type: boolean
        default: false
    secrets:
      envPAT:
        required: false
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Check out lingua-franca repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Prepare build environment
        uses: ./.github/actions/prepare-build-env
      - name: Build and package lf cli tools (nightly build)
        run: .github/scripts/package-cli.sh nightly
        shell: bash
        if: ${{ inputs.nightly == true }}
      - name: Build and package lf cli tools (regular build)
        run: .github/scripts/package-cli.sh
        shell: bash
        if: ${{ inputs.nightly != true }}
      - name: Deploy nightly release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.envPAT }}"
          automatic_release_tag: 'nightly'
          prerelease: true
          title: "Lingua Franca Nightly"
          files: |
            build_upload/*
        if: ${{ inputs.nightly == true }}
