name: C

on:
  workflow_dispatch:
  workflow_call:

env:
  # 2020.11
  vcpkgGitRef: 0bf3923f9fab4001c00f0f429682a0853b5749e0

concurrency:
  group: only-c-${{ github.ref }}-${{ github.event_path }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

jobs:
  # Run the C integration tests.
  default:
    uses: ./.github/workflows/c-tests.yml
    with:
      all-platforms: ${{ !github.event.pull_request.draft  }}
