name: Serialization tests

on:
  workflow_call:
    inputs:
      compiler-ref:
        required: false
        type: string

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Check out lingua-franca repository
        uses: actions/checkout@v3
        with:
          repository: lf-lang/lingua-franca
          submodules: true
          ref: ${{ inputs.compiler-ref }}
          fetch-depth: 0
      - name: Prepare build environment
        uses: ./.github/actions/prepare-build-env
      - name: Check out specific ref of reactor-c
        uses: actions/checkout@v3
        with:
          repository: lf-lang/reactor-c
          path: org.lflang/src/lib/c/reactor-c
          ref: ${{ inputs.runtime-ref }}
        if: ${{ inputs.runtime-ref }}
      - name: Install dependencies OS X
        run: |
          brew install coreutils
        if: ${{ runner.os == 'macOS' }}
      - name: Install RTI
        uses: ./.github/actions/install-rti
        if: ${{ runner.os == 'macOS' || runner.os == 'Linux' }}
      - name: Install Arduino Platform for MacOS
        run: |
          brew install --cask arduino
        if: ${{ runner.os == 'macOS' }}
      - name: Install Arduino Platform for Linux
        run: |
          wget "https://downloads.arduino.cc/arduino-1.8.19-linux32.tar.xz"
          tar -xvf arduino-1.8.19-linux32.tar.xz
          cd arduino-1.8.19/
          sudo ./install.sh
        if: ${{ runner.os == 'Linux' }}
      - name: Build RTI docker image
        uses: ./.github/actions/build-rti-docker
        if: ${{ runner.os == 'Linux' }}
      - name: Setup ROS2
        uses: ros-tooling/setup-ros@0.2.2
        with:
          required-ros-distributions: rolling
      - name: Install Protobuf Ubuntu
        run: |
          sudo apt-get update
          sudo apt-get install -y libprotobuf-c-dev protobuf-c-compiler protobuf-compiler libprotobuf-dev
      - name: Install LinguaFrancaBase
        run: pip3 install LinguaFrancaBase
      - name: Run serialization tests;
        run: |
          source /opt/ros/*/setup.bash
          ./gradlew test --tests org.lflang.tests.serialization.SerializationTest.*
      - name: debug-serialization-tests
        uses: lhotari/action-upterm@v1
      - name: Report to CodeCov
        uses: codecov/codecov-action@v2.1.0
        with:
          file: org.lflang.tests/build/reports/xml/jacoco
          fail_ci_if_error: false
          verbose: true
        if: ${{ !inputs.runtime-ref }}  # i.e., if this is part of the main repo's CI
